### ISSUE TITLE
simpler api

### ISSUE THREAD

**Issue by bbigras** [Koka/odbc-rs#9] opened 2017-01-25 17:46 UTC
The postgres crate has a pretty simple API https://github.com/sfackler/rust-postgres/blob/master/README.md. It would be nice to have the same with odbc-rs.

**Comment by pacman82** [comment] 2017-02-07 22:11
I feel the same way. I have not yet used the postgres crate, but certainly using ODBC should be simpler than it is right now. At the very least it should be possible in safe code. Do you have a particular use case in mind?

**Comment by brunoqc** [comment] 2017-03-14 20:13
> Do you have a particular use case in mind?

Sorry about the very late reply. I would like to use it with MSSQL.

**Comment by pacman82** [comment] 2017-03-14 21:31
I develop locally with windows 10, so I can probably help you set it up if you encounter some weird linker errors. Yet I have only used it with the Access text driver and not yet with an actual MSSQL Server.
IMHO the API has much improved since you last commented (although it has not been released yet), maybe you want to give it a try.
In the very likely case you are missing something I'd be interested to know what you miss most:
* Support for a specific Data type?
* The ability to bind buffers for fast extraction of data?
* The ability to prepare statements?
* ...

Seriously, I'd be happy to prioritize that use case in future development.

**Comment by brunoqc** [comment] 2017-03-15 14:33
> the API has much improved since you last commented (although it has not been released yet)

Yes I saw that. I tried the code from master yesterday. I develop on Linux and I was able to connect and fetch some data (with errors) using unixodbc and freetds (I have no idea what unixodbc does, in the pass I only used freetds).

One "error" was that if I did a SELECT on one column, the data didn't seems to match the real data but it looked familiar (like if I had parts of the data or if the rows weren't spitted correctly).

The other problem was that I had an utf8 error (`Err` value: Utf8Error { valid_up_to: 4 }') when I tried to SELECT another field. I have `client charset = UTF-8` in my freetds.conf but I guess MSSQL must store the data in latin1, so I'm not sure if I'm doing it correctly.

Can you get your hand on a MSSQL server (maybe there's a free one with some ms products)? If not I was thinking that I could try with MySQL or PostgreSQL. If I get the same bug, it could be easier for you to debug.

> The ability to bind buffers for fast extraction of data?

I'm not sure how this works but it sounds nice.

> The ability to prepare statements

Yes.

**Comment by pacman82** [comment] 2017-03-15 16:19
> I have no idea what unixodbc does

it is an implementation of an ODBC Driver Manager. It keeps track of all the different odbc driver `.so`s on your system so your application needs only to link against the driver manager and can decide which data source to use at runtime. TL;DR it is an indirection which allows your app to be independent from a particular database driver
>  Can you get your hand on a MSSQL server (maybe there's a free one with some ms products)?

There is and I can. However there is no Windows on travis CI so a reproducing example with something running and Linux is still nice.

Would you mind opening two issues for each Bug mentioned?

**Comment by Koka** [comment] 2017-03-15 16:23
@pacman82 I've seen people using https://www.appveyor.com for builds on windows and seems like it supports mssql. May be we could use it?

**Comment by pacman82** [comment] 2017-03-15 16:28
@Koka Never used it before, but it seems like it fits the bill. Great suggestion!

**Comment by pacman82** [comment] 2017-03-15 23:15
@brunoqc Just stumbled over [the official MS SQL Server ODBC driver](https://blogs.msdn.microsoft.com/sqlnativeclient/2016/10/20/odbc-driver-13-0-for-linux-released/) from Microsoft for Linux

**Comment by Koka** [comment] 2017-03-16 07:45
@brunoqc @pacman82 JFYI - I've just released 0.3.0 with all latest changes

**Comment by pacman82** [comment] 2017-03-16 19:51
@brunoqc I have been able to reproduce the first Bug you mentioned. See #23

**Comment by brunoqc** [comment] 2017-03-16 19:56
Nice, I'll test again.

**Comment by brunoqc** [comment] 2017-03-17 15:40
It works. Both problem seems gone. I tested with master.

**Comment by Koka** [comment] 2017-04-04 05:10
Looks like every problem mentioned in this issue was resolved, so I'm closing this.

**Closed by Koka** 2017-04-04 05:10 UTC
Labels: enhancement
